// The 8 fixed, built-in TONEBENCH presets — ported verbatim from
// docs/prototype.html. These are hardcoded and not persisted; see
// SoundSet in src/DataStore.ts for user-created, persisted presets.

import type { SynthParams } from '/src/engine/tonebenchEngine.js';

export const PRESETS: Record<string, SynthParams> = {
  LASER: {
    waveType: 'sawtooth',
    freqStart: 1800,
    freqEnd: 220,
    attack: 0.001,
    decay: 0.05,
    sustainLevel: 0.3,
    sustainTime: 0.05,
    release: 0.05,
    filterType: 'lowpass',
    filterCutoff: 4000,
    filterQ: 5,
    distortion: 10,
    delayTime: 0.15,
    delayFeedback: 0.2,
    delayMix: 0,
    reverbDecay: 0.5,
    reverbMix: 0.1,
    volume: 0.7,
  },
  EXPLOSION: {
    waveType: 'noise',
    freqStart: 100,
    freqEnd: 100,
    attack: 0.001,
    decay: 0.3,
    sustainLevel: 0.2,
    sustainTime: 0.1,
    release: 0.6,
    filterType: 'lowpass',
    filterCutoff: 800,
    filterQ: 1,
    distortion: 30,
    delayTime: 0.1,
    delayFeedback: 0.1,
    delayMix: 0,
    reverbDecay: 2.2,
    reverbMix: 0.35,
    volume: 0.9,
  },
  JUMP: {
    waveType: 'square',
    freqStart: 300,
    freqEnd: 700,
    attack: 0.001,
    decay: 0.08,
    sustainLevel: 0.4,
    sustainTime: 0.02,
    release: 0.1,
    filterType: 'lowpass',
    filterCutoff: 5000,
    filterQ: 2,
    distortion: 0,
    delayTime: 0.15,
    delayFeedback: 0.1,
    delayMix: 0,
    reverbDecay: 0.4,
    reverbMix: 0.05,
    volume: 0.7,
  },
  COIN: {
    waveType: 'square',
    freqStart: 900,
    freqEnd: 1500,
    attack: 0.001,
    decay: 0.04,
    sustainLevel: 0.5,
    sustainTime: 0.06,
    release: 0.12,
    filterType: 'none',
    filterCutoff: 4000,
    filterQ: 1,
    distortion: 0,
    delayTime: 0.1,
    delayFeedback: 0.1,
    delayMix: 0,
    reverbDecay: 0.8,
    reverbMix: 0.15,
    volume: 0.6,
  },
  HIT: {
    waveType: 'sawtooth',
    freqStart: 220,
    freqEnd: 60,
    attack: 0.001,
    decay: 0.05,
    sustainLevel: 0.3,
    sustainTime: 0.02,
    release: 0.1,
    filterType: 'lowpass',
    filterCutoff: 1200,
    filterQ: 3,
    distortion: 40,
    delayTime: 0.1,
    delayFeedback: 0.1,
    delayMix: 0,
    reverbDecay: 0.6,
    reverbMix: 0.05,
    volume: 0.8,
  },
  POWERUP: {
    waveType: 'square',
    freqStart: 300,
    freqEnd: 1200,
    attack: 0.01,
    decay: 0.15,
    sustainLevel: 0.6,
    sustainTime: 0.2,
    release: 0.25,
    filterType: 'lowpass',
    filterCutoff: 6000,
    filterQ: 1,
    distortion: 0,
    delayTime: 0.15,
    delayFeedback: 0.2,
    delayMix: 0.1,
    reverbDecay: 1.2,
    reverbMix: 0.2,
    volume: 0.7,
  },
  'UI CLICK': {
    waveType: 'sine',
    freqStart: 1200,
    freqEnd: 900,
    attack: 0.001,
    decay: 0.02,
    sustainLevel: 0.2,
    sustainTime: 0.01,
    release: 0.03,
    filterType: 'none',
    filterCutoff: 4000,
    filterQ: 1,
    distortion: 0,
    delayTime: 0.1,
    delayFeedback: 0.1,
    delayMix: 0,
    reverbDecay: 0.5,
    reverbMix: 0,
    volume: 0.5,
  },
  ALARM: {
    waveType: 'square',
    freqStart: 600,
    freqEnd: 900,
    attack: 0.05,
    decay: 0.05,
    sustainLevel: 0.8,
    sustainTime: 0.3,
    release: 0.2,
    filterType: 'bandpass',
    filterCutoff: 800,
    filterQ: 8,
    distortion: 5,
    delayTime: 0.1,
    delayFeedback: 0.1,
    delayMix: 0,
    reverbDecay: 0.8,
    reverbMix: 0.1,
    volume: 0.8,
  },
};
